/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirio.ccet.bsi.view.principais;

import br.unirio.ccet.bsi.persistence.dao.AluguelDAO;
import br.unirio.ccet.bsi.persistence.dao.impl.AluguelDAOImpl;
import br.unirio.ccet.bsi.persistence.entity.Aluguel;
import br.unirio.ccet.bsi.utils.Enums;
import br.unirio.ccet.bsi.view.TelaAgradecimentos;
import br.unirio.ccet.bsi.view.alugueis.TelaAtualizarAluguel;
import br.unirio.ccet.bsi.view.alugueis.TelaCadastroAluguel;
import br.unirio.ccet.bsi.view.alugueis.TelaVerificarAlugueis;
import br.unirio.ccet.bsi.view.vendas.TelaCadastroVenda;
import br.unirio.ccet.bsi.view.clientes.TelaCadastroCliente;
import br.unirio.ccet.bsi.view.clientes.TelaExcluirCliente;
import br.unirio.ccet.bsi.view.clientes.TelaAlterarCliente;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Yuri Lopam
 */
public class TelaPrincipalAtendente extends javax.swing.JFrame {

    private boolean avisar = true;
    
    public TelaPrincipalAtendente() {
        initComponents();  
        
        addWindowStateListener((WindowEvent arg0) -> {
            if (arg0.equals(WindowEvent.WINDOW_CLOSING)){
                avisar = false;
            }
        });
        
        Thread t = new Thread(){
            @Override
            public void run() {
                AluguelDAO aluguelDAO = new AluguelDAOImpl();
                validarDataDevolucao(aluguelDAO);
                List<Aluguel> alugueis = aluguelDAO.findAll();
                while(avisar){
                    for (Aluguel aluguel : alugueis){
                        if (aluguel.getSituacao().equals((Enums.SituacoesDoAluguel.ATRASADO).toString())){
                            JOptionPane.showMessageDialog(getParent(), "Existem aluguéis atrasados!");
                            avisar = true;
                        } else {
                            avisar = false;
                        }
                    }
                    try {
                        Thread.sleep(10 * 1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }

            private void validarDataDevolucao(AluguelDAO aluguelDAO) {
                List<Aluguel> alugueis = aluguelDAO.findAll();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date date = new Date();
                for (Aluguel aluguel : alugueis){
                    Date dataAluguel = new Date(aluguel.getDataDevolucao().getTime());
                    if (!aluguel.getSituacao().equals(Enums.SituacoesDoAluguel.DEVOLVIDO)){
                        if (dataAluguel.before(date)){
                            aluguel.setSituacao((Enums.SituacoesDoAluguel.ATRASADO).toString());
                            aluguel.setCodigoAluguel(aluguel.getCodigoAluguel());
                            aluguel.setCliente(aluguel.getCliente());
                            aluguel.setDataDevolucao(aluguel.getDataDevolucao());
                            aluguel.setDataEntrega(aluguel.getDataEntrega());
                            aluguel.setDataAluguel(aluguel.getDataAluguel());
                            aluguel.setFormaPagamento(aluguel.getFormaPagamento());
                            aluguel.setObservacoes(aluguel.getObservacoes());
                            aluguel.setPrecoTotal(aluguel.getPrecoTotal());
                            aluguel.setVendedor(aluguel.getVendedor());
                            aluguelDAO.update(aluguel);
                        }
                    }
                }
            }
        };
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MrMayhem");
        setResizable(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/group.png"))); // NOI18N
        jMenu2.setText("Clientes");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/group_add.png"))); // NOI18N
        jMenuItem5.setText("Cadastrar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/group_edit.png"))); // NOI18N
        jMenuItem6.setText("Alterar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/group_delete.png"))); // NOI18N
        jMenuItem7.setText("Excluir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/cart.png"))); // NOI18N
        jMenu4.setText("Pedido de Vendas/Aluguéis");

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/cart_add.png"))); // NOI18N
        jMenuItem13.setText("Cadastrar Venda");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/date_add.png"))); // NOI18N
        jMenuItem16.setText("Cadastrar Aluguel");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/date_edit.png"))); // NOI18N
        jMenuItem17.setText("Atualizar Aluguel");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/date_magnify.png"))); // NOI18N
        jMenuItem18.setText("Verificar Alugueis");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem18);

        jMenuBar1.add(jMenu4);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/information.png"))); // NOI18N
        jMenu9.setText("Sobre");

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unirio/ccet/bsi/images/thumb_up.png"))); // NOI18N
        jMenuItem14.setText("Agradecimentos");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem14);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaCadastroCliente telaCadastroCliente = new TelaCadastroCliente();
        jDesktopPane1.add(telaCadastroCliente);
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        TelaAlterarCliente telaAlterarCliente = new TelaAlterarCliente();
        jDesktopPane1.add(telaAlterarCliente);
        telaAlterarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        TelaExcluirCliente telaExcluirCliente = new TelaExcluirCliente();
        jDesktopPane1.add(telaExcluirCliente);
        telaExcluirCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        TelaCadastroVenda telaCadastroVendas = new TelaCadastroVenda();
        jDesktopPane1.add(telaCadastroVendas);
        telaCadastroVendas.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        TelaCadastroAluguel telaCadastroAluguel = new TelaCadastroAluguel();
        jDesktopPane1.add(telaCadastroAluguel);
        telaCadastroAluguel.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        TelaAtualizarAluguel telaAtualizarAluguel = new TelaAtualizarAluguel();
        jDesktopPane1.add(telaAtualizarAluguel);
        telaAtualizarAluguel.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        TelaVerificarAlugueis telaVerificarAlugueis = new TelaVerificarAlugueis();
        jDesktopPane1.add(telaVerificarAlugueis);
        telaVerificarAlugueis.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        TelaAgradecimentos telaAgradecimentos = new TelaAgradecimentos();
        jDesktopPane1.add(telaAgradecimentos);
        telaAgradecimentos.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables

}
