/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirio.ccet.bsi.view.envios;

import br.unirio.ccet.bsi.controller.Login;
import br.unirio.ccet.bsi.utils.Mail;
import br.unirio.ccet.bsi.utils.Pdf;
import br.unirio.ccet.bsi.view.funcionarios.TelaPesquisaFuncionario;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.apache.commons.lang3.StringUtils;


/**
 *
 * @author Yuri Lopam
 */
public class TelaEnvioRelatorio extends javax.swing.JInternalFrame {

    private final JTable jTable1;

    /**
     * Creates new form TelaPesquisaFuncionario
     */
    public TelaEnvioRelatorio(JTable jTable1) {
        initComponents();
        this.jTable1 = jTable1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoEmailDestinatario = new javax.swing.JTextField();
        campoAssunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoMensagem = new javax.swing.JTextArea();
        botaoEnviarEmail = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        campoMensagem.setColumns(20);
        campoMensagem.setRows(5);
        jScrollPane1.setViewportView(campoMensagem);

        botaoEnviarEmail.setLabel("Enviar e-mail");
        botaoEnviarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarEmailActionPerformed(evt);
            }
        });

        jLabel1.setText("E-Mail do destinatário:");

        jLabel2.setText("Assunto:");

        jLabel3.setText("Mensagem:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(botaoEnviarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoEmailDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoEmailDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEnviarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarEmailActionPerformed
        if (formularioEnvioValidado()){
            DateFormat dateFormat = new SimpleDateFormat("yyyyMMddHHmmss");
            Date date = new Date();
            String nomeDoRelatorio = dateFormat.format(date);
            String nomeDoRelatorioPdf = nomeDoRelatorio+".pdf";
            Pdf pdf = new Pdf(jTable1, nomeDoRelatorioPdf);
            Mail mail = new Mail();
            try {
                campoEmailDestinatario.setEditable(false);
                campoAssunto.setEditable(false);
                campoMensagem.setEditable(false);
                botaoEnviarEmail.setEnabled(false);
                mail.enviarEmailComAnexo(Login.getIdUsuario()+"mrmayhem@gmail.com", "1wdvfe@3", campoEmailDestinatario.getText(), 
                        campoAssunto.getText(), campoMensagem.getText(), nomeDoRelatorioPdf);
            } catch (IOException ex) {
                Logger.getLogger(TelaPesquisaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
            resetarCampos();
            JOptionPane.showMessageDialog(TelaEnvioRelatorio.this, "E-mail enviado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(TelaEnvioRelatorio.this, "Preencha todos os campos para enviar seu email.");
        }
    }//GEN-LAST:event_botaoEnviarEmailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button botaoEnviarEmail;
    private javax.swing.JTextField campoAssunto;
    private javax.swing.JTextField campoEmailDestinatario;
    private javax.swing.JTextArea campoMensagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private boolean formularioEnvioValidado() {
        return !StringUtils.isEmpty(campoEmailDestinatario.getText())
                && !StringUtils.isEmpty(campoAssunto.getText())
                && !StringUtils.isEmpty(campoMensagem.getText());
    }

    private void resetarCampos() {
        campoEmailDestinatario.setEditable(true);
        campoAssunto.setEditable(true);
        campoMensagem.setEditable(true);
        campoEmailDestinatario.setText(null);
        campoAssunto.setText(null);
        campoMensagem.setText(null);
        botaoEnviarEmail.setEnabled(true);
    }
}
